export const IS_AUTHENTICATED = 'IS_AUTHENTICATED'
export const CREATE_ACCOUNT_SUCCESS = 'CREATE_ACCOUNT_SUCCESS'
export const CLEAR_ERROR_MESSAGE = 'CLEAR_ERROR_MESSAGE'
export const DISPLAY_ERROR_MESSAGE = 'DISPLAY_ERROR_MESSAGE'
export const PRODUCT_CREATED = 'PRODUCT_CREATED'
export const CATEGORIES_LOADING = 'CATEGORIES_LOADING'
export const CATEGORIES_FETCHED = 'CATEGORIES_FETCHED'

export const PRODUCT_ONSALE = 'PRODUCT_ONSALE'
export const PRODUCT_TRENDING = 'PRODUCT_TRENDING'
export const PRODUCT_FEATURED = 'PRODUCT_FEATURED'
export const PROFILE_PRODUCTS = 'PROFILE_PRODUCTS'

export const FETCH_BOOKMARKS = 'FETCH_BOOKMARKS'
export const BOOKMARK_PRODUCT = 'BOOKMARK_PRODUCT'
export const UN_BOOKMARK_PRODUCT = 'UN_BOOKMARK_PRODUCT'

export const ADD_BOOKMARK = 'ADD_BOOKMARK'

export const FETCH_NOTIFICATIONS = 'FETCH_NOTIFICATIONS'

export const UPDATE_PROFILE = 'UPDATE_PROFILE'
