export const IS_AUTHENTICATED = "IS_AUTHENTICATED";
export const CREATE_ACCOUNT_SUCCESS = "CREATE_ACCOUNT_SUCCESS";
export const CLEAR_ERROR_MESSAGE = "CLEAR_ERROR_MESSAGE";
export const DISPLAY_ERROR_MESSAGE = "DISPLAY_ERROR_MESSAGE";
export const PRODUCT_CREATED = "PRODUCT_CREATED";
export const CATEGORIES_LOADING = "CATEGORIES_LOADING";
export const CATEGORIES_FETCHED = "CATEGORIES_FETCHED";

export const PRODUCT_ONSALE = "PRODUCT_ONSALE";
export const PRODUCT_TRENDING = "PRODUCT_TRENDING";
export const PRODUCT_FEATURED = "PRODUCT_FEATURED";
