export const SHOW_SPINNER = 'SHOW_SPINNER'
export const HIDE_SPINNER = 'HIDE_SPINNER'
export const IS_AUTHENTICATED = 'IS_AUTHENTICATED'
export const CREATE_ACCOUNT_SUCCESS = 'CREATE_ACCOUNT_SUCCESS'
export const CLEAR_ERROR_MESSAGE = 'CLEAR_ERROR_MESSAGE'
export const DISPLAY_ERROR_MESSAGE = 'DISPLAY_ERROR_MESSAGE'
export const PRODUCT_CREATED = 'PRODUCT_CREATED'
export const CLEAR_PRODUCT = 'CLEAR_PRODUCT'
export const CATEGORIES_LOADING = 'CATEGORIES_LOADING'
export const CATEGORIES_FETCHED = 'CATEGORIES_FETCHED'

export const PRODUCT_ONSALE = 'PRODUCT_ONSALE'
export const FOLLOWING_PROFILE_PRODUCTS = 'FOLLOWING_PROFILE_PRODUCTS'
export const PRODUCT_TRENDING = 'PRODUCT_TRENDING'
export const PRODUCT_FEATURED = 'PRODUCT_FEATURED'
export const PROFILE_PRODUCTS = 'PROFILE_PRODUCTS'

export const FETCH_BOOKMARKS = 'FETCH_BOOKMARKS'
export const BOOKMARK_PRODUCT = 'BOOKMARK_PRODUCT'
export const UN_BOOKMARK_PRODUCT = 'UN_BOOKMARK_PRODUCT'

export const ADD_BOOKMARK = 'ADD_BOOKMARK'

export const FETCH_NOTIFICATIONS = 'FETCH_NOTIFICATIONS'
export const FOLLOWING_USER_PROFILE = 'FOLLOWING_USER_PROFILE'
export const FETCH_USER_FOLLOWERS = 'FETCH_USER_FOLLOWERS'
export const FETCH_USER_FOLLOWINGS = 'FETCH_USER_FOLLOWINGS'
export const UPDATE_PASSWORD = 'UPDATE_PASSWORD'

export const LOGGED_USER_PROFILE = 'LOGGED_USER_PROFILE'
export const UPDATE_PROFILE = 'UPDATE_PROFILE'

export const FETCH_PROVINCE = 'FETCH_PROVINCE'

export const FETCH_CITY = 'FETCH_CITY'

export const FETCH_COURIERS = 'FETCH_COURIERS'

export const FETCH_CART = 'FETCH_CART'
export const ADD_TO_CART = 'ADD_TO_CART'
export const BID_FOR_PRODUCT = 'BID_FOR_PRODUCT'
export const CHECKOUT = 'CHECKOUT'
export const FETCH_SOLD_ORDER_HISTORY = 'FETCH_SOLD_ORDER_HISTORY'
export const FETCH_BOUGHT_ORDER_HISTORY = 'FETCH_BOUGHT_ORDER_HISTORY'
export const FETCH_SHIPPING_COST = 'FETCH_SHIPPING_COST'
export const REVIEW_PRODUCT = 'REVIEW_PRODUCT'

export const GET_PRODUCT_REVIEW = 'GET_PRODUCT_REVIEW'
export const GET_WALLET_AMOUNT = 'GET_WALLET_AMOUNT'
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS'

export const LOG_OUT = 'LOG_OUT'

export const SET_CHAT_USER = 'SET_CHAT_USER'
export const SET_ROOM = 'SET_ROOM'
export const IS_TYPING = 'IS_TYPING'
export const IS_NOT_TYPING = 'IS_NOT_TYPING'
export const ON_RECEIVE_MESSAGE = 'ON_RECEIVE_MESSAGE'
export const SEND_MESSAGE = 'SEND_MESSAGE'
export const SEND_MESSAGE_ERROR = 'SEND_MESSAGE_ERROR'
